language: cpp
sudo: false
dist: trusty
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
    env:
      - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
script:
  - mkdir build
  - cd build && cmake .. && make -j && make test
before_script:
  - eval "${MATRIX_EVAL}"